version: '3.8'

services:
  backend:
    build: .
    ports:
      - "10000:10000"
    environment:
      - NODE_ENV=development
      - PORT=10000
      - MONGODB_URI=mongodb+srv://uday:uday@cluster0.n2vzkur.mongodb.net/student-sentience?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=your-jwt-secret-here
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:10000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
