[build]
  command = "cd frontend && npm run build"
  publish = "frontend/dist"

[build.environment]
  VITE_API_URL = "https://sentience.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 