[build]
  base = "."
  command = "./build.sh"
  publish = "frontend/dist"

[build.environment]
  VITE_API_URL = "https://sentience.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 