services:
  - type: web
    name: sentience-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    dockerfilePath: null
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: "mongodb+srv://uday:uday@cluster0.n2vzkur.mongodb.net/student-sentience?retryWrites=true&w=majority&appName=Cluster0"
      - key: JWT_SECRET
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true 